version: '3.8'

services:
  backend:
    build:
      context: ./erp_backend
      dockerfile: Dockerfile
    container_name: erp_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./erp_backend:/app
      - erp_data:/data
    env_file:
      - ./erp_backend/.env
    environment:
      - DATABASE_URL=sqlite:////app/erp.db
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - erp_network

  frontend:
    build:
      context: ./erp_frontend
      dockerfile: Dockerfile
    container_name: erp_frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./erp_frontend:/app
    env_file:
      - ./erp_frontend/.env
    environment:
      - API_BASE_URL=http://backend:8000/api
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - erp_network

networks:
  erp_network:
    driver: bridge

volumes:
  erp_data:
